"""Quality profiles and the recommendation rule engine."""

from .engine import (
    Judgement,
    apply_filters,
    choice_index,
    explain,
    matches,
    preferred_indexer_candidates,
    rank,
    recommend,
    rejection,
)
from .models import (
    AudioMatchRule,
    Choice,
    ChoiceMatch,
    ExcludePrereleaseRule,
    HdrMatchRule,
    KeywordExcludeRule,
    QualityProfile,
    QualityRule,
    RepackProperPriorityRule,
    ResolutionOrderRule,
    RuleType,
    SizeCapGbRule,
    SizeDirection,
    SizeRule,
    SourceOrderRule,
    TieBreak,
    default_profile,
)

__all__ = [
    "AudioMatchRule",
    "Choice",
    "ChoiceMatch",
    "ExcludePrereleaseRule",
    "HdrMatchRule",
    "Judgement",
    "KeywordExcludeRule",
    "QualityProfile",
    "QualityRule",
    "RepackProperPriorityRule",
    "ResolutionOrderRule",
    "RuleType",
    "SizeCapGbRule",
    "SizeDirection",
    "SizeRule",
    "SourceOrderRule",
    "TieBreak",
    "apply_filters",
    "choice_index",
    "default_profile",
    "explain",
    "matches",
    "preferred_indexer_candidates",
    "rank",
    "recommend",
    "rejection",
]
