"""initial schema

Revision ID: 5c8aefe6d516
Revises: 
Create Date: 2026-08-18 02:52:39.130931
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '5c8aefe6d516'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seerr_url', sa.String(length=512), nullable=True),
    sa.Column('prowlarr_url', sa.String(length=512), nullable=True),
    sa.Column('prowlarr_api_key', sa.String(length=256), nullable=True),
    sa.Column('preferred_indexer_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_config_singleton'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seerr_user_id', sa.Integer(), nullable=False),
    sa.Column('plex_username', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_seerr_user_id'), ['seerr_user_id'], unique=True)

    op.create_table('actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('download_client_id', sa.Integer(), nullable=False),
    sa.Column('quality_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quality_profile_id'], ['quality_profiles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('grabs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('release_title', sa.String(length=1024), nullable=False),
    sa.Column('release_guid', sa.String(length=1024), nullable=False),
    sa.Column('indexer_id', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grabs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grabs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_grabs_user_id'), ['user_id'], unique=False)

    op.create_table('permissions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'action_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    with op.batch_alter_table('grabs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grabs_user_id'))
        batch_op.drop_index(batch_op.f('ix_grabs_created_at'))

    op.drop_table('grabs')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))

    op.drop_table('activity_log')
    op.drop_table('actions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_seerr_user_id'))

    op.drop_table('users')
    op.drop_table('quality_profiles')
    op.drop_table('config')
    # ### end Alembic commands ###
