"""notification preferences and apns devices

Note that ``notification_preferences`` is deliberately left empty: a type with
no row is enabled, so every notification type is on for existing installs the
moment they upgrade, with nothing to seed here and nothing to backfill when a
later release adds another one.

Revision ID: 803cf5974bf3
Revises: e5a1c9f0b3d7
Create Date: 2026-08-26 09:02:08.815835
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '803cf5974bf3'
down_revision: str | None = 'e5a1c9f0b3d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('notification_type')
    )
    op.create_table('apns_devices',
    sa.Column('device_token', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=16), server_default='production', nullable=False),
    sa.Column('device_name', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_token')
    )
    with op.batch_alter_table('apns_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apns_devices_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apns_team_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('apns_key_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('apns_bundle_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('apns_private_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_column('apns_private_key')
        batch_op.drop_column('apns_bundle_id')
        batch_op.drop_column('apns_key_id')
        batch_op.drop_column('apns_team_id')

    with op.batch_alter_table('apns_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apns_devices_user_id'))

    op.drop_table('apns_devices')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
