"""request action, admin sessions

Revision ID: 80624f214cdc
Revises: 5c8aefe6d516
Create Date: 2026-08-18 03:10:50.505127
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '80624f214cdc'
down_revision: str | None = '5c8aefe6d516'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_sessions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False))
        batch_op.alter_column('download_client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quality_profile_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_check_constraint('ck_action_targets_required_unless_system', 'is_system = 1 OR (download_client_id IS NOT NULL AND quality_profile_id IS NOT NULL)')

    with op.batch_alter_table('grabs', schema=None) as batch_op:
        batch_op.alter_column('release_title',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grabs', schema=None) as batch_op:
        batch_op.alter_column('release_title',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)

    with op.batch_alter_table('actions', schema=None) as batch_op:
        batch_op.drop_constraint('ck_action_targets_required_unless_system', type_='check')
        batch_op.alter_column('quality_profile_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('download_client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('is_system')

    with op.batch_alter_table('admin_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_sessions_user_id'))

    op.drop_table('admin_sessions')
    # ### end Alembic commands ###
