"""persist plex token sessions

Revision ID: 9c25af52f7b5
Revises: c1303504a057
Create Date: 2026-08-18 04:15:26.367072
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '9c25af52f7b5'
down_revision: str | None = 'c1303504a057'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plex_token_sessions',
    sa.Column('token_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_fingerprint')
    )
    with op.batch_alter_table('plex_token_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plex_token_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plex_token_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plex_token_sessions_user_id'))

    op.drop_table('plex_token_sessions')
    # ### end Alembic commands ###
