"""audiobook progress

Where each user is in each audiobook, independent of whether it is aligned.
New table only.

Revision ID: a634b1eb30b1
Revises: f95a599b0fa7
Create Date: 2026-09-28 23:26:25.610870
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a634b1eb30b1'
down_revision: str | None = 'f95a599b0fa7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobook_progress',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plex_server_id', sa.String(length=64), nullable=False),
    sa.Column('rating_key', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('track_rating_key', sa.String(length=32), nullable=True),
    sa.Column('track_offset', sa.Float(), nullable=True),
    sa.Column('finished', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('listened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plex_server_id', 'rating_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audiobook_progress')
    # ### end Alembic commands ###
