"""audiobook alignment

Three new tables and nothing else touched: jobs (one epub upload each, kept
after they finish), finished alignments keyed by Plex server and album
ratingKey, and their sentences in gzipped chunks.

Revision ID: f95a599b0fa7
Revises: c4d9b7e21f06
Create Date: 2026-09-28 22:40:55.999597
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f95a599b0fa7'
down_revision: str | None = 'c4d9b7e21f06'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobook_alignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plex_server_id', sa.String(length=64), nullable=False),
    sa.Column('rating_key', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('tracks', sa.JSON(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('epub_title', sa.String(length=512), nullable=True),
    sa.Column('epub_author', sa.String(length=512), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plex_server_id', 'rating_key')
    )
    with op.batch_alter_table('audiobook_alignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audiobook_alignments_library_id'), ['library_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audiobook_alignments_rating_key'), ['rating_key'], unique=False)

    op.create_table('audiobook_chunks',
    sa.Column('alignment_id', sa.Integer(), nullable=False),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('start', sa.Float(), nullable=True),
    sa.Column('end', sa.Float(), nullable=True),
    sa.Column('first_sentence', sa.Integer(), nullable=False),
    sa.Column('last_sentence', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['alignment_id'], ['audiobook_alignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alignment_id', 'n')
    )
    op.create_table('audiobook_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plex_server_id', sa.String(length=64), nullable=False),
    sa.Column('rating_key', sa.String(length=32), nullable=False),
    sa.Column('library_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=128), nullable=True),
    sa.Column('progress', sa.Float(), server_default='0', nullable=False),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('secret', sa.String(length=64), nullable=False),
    sa.Column('tracks', sa.JSON(), nullable=False),
    sa.Column('epub_title', sa.String(length=512), nullable=True),
    sa.Column('epub_author', sa.String(length=512), nullable=True),
    sa.Column('epub_words', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heard_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audiobook_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audiobook_jobs_rating_key'), ['rating_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_audiobook_jobs_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiobook_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_audiobook_jobs_rating_key'))

    op.drop_table('audiobook_jobs')
    op.drop_table('audiobook_chunks')
    with op.batch_alter_table('audiobook_alignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audiobook_alignments_rating_key'))
        batch_op.drop_index(batch_op.f('ix_audiobook_alignments_library_id'))

    op.drop_table('audiobook_alignments')
    # ### end Alembic commands ###
