"""Installing the aligner's runtime into its volume, on an admin's request.

Nothing heavy ships in the image. When audiobooks are enabled, this downloads
exactly the files pinned in ``runtime_lock.json`` — every wheel by URL and
SHA-256, the model at a fixed revision — into ``runtime/``, builds a venv from
them with no index access at all, and checks it imports. Downloads resume
after an interruption; a finished install is only swapped in once it has
passed its check, so a failed update leaves the working runtime in place.

The lock is generated by ``scripts/lock_aligner_runtime.py``; bump versions
there, not here.
"""

from __future__ import annotations

import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
from collections.abc import Callable
from importlib import resources
from pathlib import Path
from typing import Any

from .protocol import AlignPaths

LOCAL_WHEELS_ENV = "CPLUS_ALIGN_LOCAL_WHEELS"
DEFAULT_LOCAL_WHEELS = "/opt/cplus-align/wheels"

#: What unpacking the wheels roughly adds on top of their download size (torch
#: alone expands ~4x). Checked against free space before anything is fetched.
INSTALL_EXPANSION = 1_300_000_000

Report = Callable[[dict[str, Any]], None]


class InstallError(RuntimeError):
    pass


def load_lock() -> dict[str, Any]:
    return json.loads(resources.files("cplus_align").joinpath("runtime_lock.json").read_text())


def arch() -> str:
    machine = platform.machine().lower()
    return {"amd64": "x86_64", "arm64": "aarch64"}.get(machine, machine)


def local_wheels() -> list[Path]:
    """Wheels built into the image (the aligner's compiled extension)."""
    folder = Path(os.environ.get(LOCAL_WHEELS_ENV, DEFAULT_LOCAL_WHEELS))
    return sorted(folder.glob("*.whl")) if folder.is_dir() else []


def _local_identity() -> list[str]:
    folder = Path(os.environ.get(LOCAL_WHEELS_ENV, DEFAULT_LOCAL_WHEELS))
    stamp = folder / "SOURCE"
    # Filenames plus the pinned source commit, not the wheels' bytes: a rebuild
    # of the same commit produces a byte-different wheel and must not count as
    # a runtime change.
    names = [p.name for p in local_wheels()]
    return [*names, stamp.read_text().strip() if stamp.exists() else ""]


def runtime_id(lock: dict[str, Any] | None = None) -> str:
    """Identifies one exact runtime: this lock, this architecture, this Python.

    ``state.json`` records the id it was installed under; a different id means
    the image moved on and the runtime needs updating.
    """
    lock = lock or load_lock()
    payload = {
        "wheels": lock.get("wheels", {}).get(arch()),
        "model": lock.get("model"),
        "python": f"{sys.version_info.major}.{sys.version_info.minor}",
        "local": _local_identity(),
    }
    return hashlib.sha256(json.dumps(payload, sort_keys=True).encode()).hexdigest()[:16]


def files_for(lock: dict[str, Any], paths: AlignPaths) -> list[dict[str, Any]]:
    """Every file the runtime needs, with where it goes."""
    wheels = lock.get("wheels", {}).get(arch())
    if not wheels:
        raise InstallError(f"There is no aligner runtime for this CPU architecture ({arch()}).")
    out = [
        {**w, "dest": str(paths.downloads / "wheels" / w["filename"]), "kind": "wheel"}
        for w in wheels
    ]
    out += [
        {**f, "dest": str(paths.model_dir / f["name"]), "kind": "model"}
        for f in lock["model"]["files"]
    ]
    return out


def _verified_file(paths: AlignPaths) -> Path:
    return paths.runtime / "verified.json"


def missing_files(lock: dict[str, Any], paths: AlignPaths) -> list[dict[str, Any]]:
    """Files not yet present and verified — what an install or update must download."""
    from .protocol import read_json

    verified = read_json(_verified_file(paths)) or {}
    out = []
    for item in files_for(lock, paths):
        dest = Path(item["dest"])
        if (
            dest.exists()
            and dest.stat().st_size == item["size"]
            and verified.get(str(dest)) == item["sha256"]
        ):
            continue
        out.append(item)
    return out


def download_size(lock: dict[str, Any] | None = None, paths: AlignPaths | None = None) -> int:
    """Bytes an install would fetch right now (everything, if ``paths`` is unknown)."""
    lock = lock or load_lock()
    if paths is None:
        wheels = lock.get("wheels", {}).get(arch()) or []
        return sum(w["size"] for w in wheels) + sum(f["size"] for f in lock["model"]["files"])
    return sum(item["size"] for item in missing_files(lock, paths))


def _fetch(item: dict[str, Any], on_bytes: Callable[[int], None], attempts: int = 8) -> None:
    dest = Path(item["dest"])
    dest.parent.mkdir(parents=True, exist_ok=True)
    part = dest.with_name(dest.name + ".part")
    failures = 0
    while True:
        digest = hashlib.sha256()
        have = 0
        if part.exists():
            with open(part, "rb") as handle:
                while chunk := handle.read(1 << 20):
                    digest.update(chunk)
                    have += len(chunk)
        if have > item["size"]:
            part.unlink()
            continue
        if have < item["size"]:
            request = urllib.request.Request(item["url"], headers={"User-Agent": "cplus-aligner"})
            if have:
                request.add_header("Range", f"bytes={have}-")
            try:
                with urllib.request.urlopen(request, timeout=60) as response:
                    if have and response.status != 206:
                        part.unlink()
                        continue
                    with open(part, "ab") as handle:
                        while chunk := response.read(1 << 20):
                            handle.write(chunk)
                            digest.update(chunk)
                            have += len(chunk)
                            on_bytes(len(chunk))
            except (urllib.error.URLError, OSError) as exc:
                failures += 1
                if failures >= attempts:
                    raise InstallError(f"Couldn't download {dest.name}: {exc}") from exc
                time.sleep(min(60, 2**failures))
                continue
        if have == item["size"]:
            if digest.hexdigest() != item["sha256"]:
                part.unlink()
                raise InstallError(f"{dest.name} did not match its pinned checksum.")
            os.replace(part, dest)
            return
        failures += 1
        if failures >= attempts:
            raise InstallError(f"Couldn't download {dest.name}: the connection kept dropping.")


def _run(cmd: list[str], what: str, timeout: int = 1800) -> None:
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout).strip().splitlines()[-5:]
        raise InstallError(f"{what} failed: {' / '.join(tail) or proc.returncode}")


SMOKE_TEST = (
    "import numpy, torch, transformers, nltk, imageio_ffmpeg, subprocess;"
    "from ctc_forced_aligner import forced_align;"
    "subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(), '-version'], check=True,"
    " capture_output=True);"
    "print(torch.__version__)"
)


def disk_usage(path: Path) -> int:
    total = 0
    for root, _dirs, files in os.walk(path):
        for name in files:
            try:
                total += os.lstat(os.path.join(root, name)).st_size
            except OSError:
                pass
    return total


def install(paths: AlignPaths, report: Report) -> dict[str, Any]:
    """Download, build and check the runtime. Returns the fields for ``state.json``."""
    from .protocol import read_json, write_json

    lock = load_lock()
    todo = missing_files(lock, paths)
    total = sum(item["size"] for item in todo)
    paths.runtime.mkdir(parents=True, exist_ok=True)
    free = shutil.disk_usage(paths.runtime).free
    if free < total + INSTALL_EXPANSION:
        raise InstallError(
            f"Not enough disk space: the download and install need about "
            f"{(total + INSTALL_EXPANSION) / 1e9:.1f} GB and {free / 1e9:.1f} GB is free."
        )

    done = 0
    last = 0.0

    def on_bytes(n: int) -> None:
        nonlocal done, last
        done += n
        now = time.monotonic()
        if now - last >= 1.0:
            last = now
            report({"stage": "download", "done": done, "total": total, "label": "Downloading"})

    report({"stage": "download", "done": 0, "total": total, "label": "Downloading"})
    verified = read_json(_verified_file(paths)) or {}
    for item in todo:
        _fetch(item, on_bytes)
        verified[item["dest"]] = item["sha256"]
        write_json(_verified_file(paths), verified)
    report({"stage": "install", "done": total, "total": total, "label": "Installing"})

    new = paths.runtime / "venv.new"
    shutil.rmtree(new, ignore_errors=True)
    _run([sys.executable, "-m", "venv", str(new)], "Creating the Python environment")
    wheels = [item["dest"] for item in files_for(lock, paths) if item["kind"] == "wheel"]
    _run(
        [
            str(new / "bin" / "python"), "-m", "pip", "install",
            "--no-index", "--no-deps", "--disable-pip-version-check", "--no-cache-dir",
            *wheels, *(str(p) for p in local_wheels()),
        ],
        "Installing packages",
    )  # fmt: skip
    report({"stage": "check", "done": total, "total": total, "label": "Checking"})
    _run([str(new / "bin" / "python"), "-c", SMOKE_TEST], "Checking the install", timeout=300)

    old = paths.runtime / "venv.old"
    shutil.rmtree(old, ignore_errors=True)
    if paths.venv.exists():
        os.replace(paths.venv, old)
    os.replace(new, paths.venv)
    shutil.rmtree(old, ignore_errors=True)
    # The wheels are installed; keeping them would only hold ~250 MB of disk.
    shutil.rmtree(paths.downloads, ignore_errors=True)
    verified = {k: v for k, v in verified.items() if not k.startswith(str(paths.downloads))}
    write_json(_verified_file(paths), verified)
    return {"runtime": runtime_id(lock), "disk": disk_usage(paths.runtime)}


def uninstall(paths: AlignPaths) -> None:
    for target in (paths.venv, paths.runtime / "venv.new", paths.runtime / "venv.old"):
        shutil.rmtree(target, ignore_errors=True)
    shutil.rmtree(paths.model_dir, ignore_errors=True)
    shutil.rmtree(paths.downloads, ignore_errors=True)
    _verified_file(paths).unlink(missing_ok=True)
